language: cpp
sudo: false
addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - libboost1.55-all-dev

cache:
  - apt

before_script:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - mkdir build

script: cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && make && ./ut
